<a href="03.md">next</a>
<h2>Error</h2>

<div>
В js существует специальный объект <code>Error</code> для обработки ошибок.
Например попытка обращения к несуществующей переменной сгенирирует следующее:
</div>

<div>
<img src="media/07-1.png">
</div>

<div>
Ошибка на примере относиться к типу ReferenceError (ссылки или обращения).
Предусмотрены и иные виды ошибок среди которых: SyntaxError, URIError, InternalError (js engine, к примеру: “too much recursion”).
На ряду со встроенными существует возможность создавать и кастомные ошибки при помощи специального объекта Error.
</div>

<div>
На примере создана кастомная ошибка, а затем вызвана по средствам оператора <code>throw</code>.
</div>

<div>
<img src="media/07-2.png">
</div>

<h3>try, catch</h3>

<div>
Для обработки ошибок существует специальная конструкция <code>try - catch - finally</code>.
Блок <code>finally</code> не является обязательным.
В случае его наличия код в рамках этого блока выполнится <strong>в любом случае</strong>,
после обработки основных блоков (в том числе и если в одном из блоков кода была выполнена команда return,
в таком случае сперва будет выполнен код из блока finally).
</div>

<div>
Если код в блоке <code>try</code> выполняется без ошибок, блок <code>catch</code> игнорируется.
Если же ошибка генерируется, то мы попадем в блок <code>catch</code>, а в аргумент попадет сама ошибка.
</div>

<div>
<img src="media/07-3.png">
</div>

<a href="01.md">prev</a>
<br/>
<a href="00.md">plan</a>
